### ISSUE TITLE
Internal Error wher search user

### ISSUE THREAD

**Issue by NokSuKao** [f0y/due_date_reminder#15]
Hi,

i installed the plugin in a redmine 1.4.x version. After the installation im getting an internal server error
wher adding/searching a watcher or search an user in Administration->User.

<pre>
NoMethodError (undefined method `call' for nil:NilClass):
  app/controllers/users_controller.rb:44:in `index'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/utils.rb:479:in `safe_fork'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb:180:in `start'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/src/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/src/passenger-3.0.13/helper-scripts/passenger-spawn-server:99

Rendering /usr/share/redmine-1.4.0/public/500.html (500 Internal Server Error)

</pre>

Could you fix it?

NokSuKao

**Comment by f0y** [comment]
Are you sure that the error is related to the plugin? I do not see it in logs.

**Comment by NokSuKao** [comment]
i uninstalled the all my plugins and everythingworks fine. Then i installed the plugin and the user search doesn't work.

**Comment by f0y** [comment]
Do you have any other plugins installed?

On Mon, Sep 24, 2012 at 4:17 PM, NokSuKao notifications@github.com wrote:

> i uninstalled the all my plugins and everythingworks fine. Then i
> installed the plugin and the user search doesn't work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/due_date_reminder/issues/15#issuecomment-8816787.

## 

Best Wishes,
Oleg Kandaurov

**Comment by NokSuKao** [comment]
no, i still have only the due date reminder plugin installed

**Comment by f0y** [comment]
Do you still have the issue?

**Comment by NokSuKao** [comment]
Yes of course, or have you changed the something?
