### ISSUE TITLE
undefined method `active_record' with redmine 2.1, ruby 1.9.3

### ISSUE THREAD

**Issue by pafcioooo** [f0y/due_date_reminder#21]
I have running redmine 2.1.3 (latest stable). I follow install instructions for the plugin. When I executed bundle exec rake redmine:plugins:migrate RAILS_ENV=production, it first give me an error about missing simplecov gem, but after I issue bundle install, next execute of bundle exec rake redmine:plugins:migrate RAILS_ENV=production gives a following error:
`(in /usr/local/share/redmine-2.1)
rake aborted!
undefined method `active_record' for #<Rails::Application::Configuration:0x00000002b7ae10>
/var/lib/gems/1.9.1/gems/railties-3.2.9/lib/rails/railtie/configuration.rb:85:in `method_missing'
(See full trace by running task with --trace)`

**Comment by f0y** [comment]
Well. It seems that only you have the issue. Maybe something wrong with your redmine installation?

**Comment by a-stangl** [comment]
Had the same issue: http://stackoverflow.com/questions/18788866/redmine-on-gentoo-undefined-method-active-record-for-railsapplicationco/18832305#18832305

**Comment by Peneheals** [comment]
Same here after a succesful bundle install:

[14:13:09] [0.19]:plugins/due_date_reminder [755|12 file|68K](redmine-2.x) $ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
rake aborted!
NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x000000023f3ae8>
.rvm/gems/ruby-1.9.3-p547/gems/railties-4.1.6/lib/rails/railtie/configuration.rb:95:in`method_missing'
config/application.rb:35:in `<class:Application>'
config/application.rb:13:in`module:RedmineApp'
config/application.rb:12:in `<top (required)>'
Rakefile:5:in`require'
Rakefile:5:in `<top (required)>'
.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in`eval'
.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

System:

Environment:
  Redmine version                2.5.2.stable
  Ruby version                   1.9.3-p547 (2014-05-14) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
Redmine plugins:
  AgileDwarf                     0.0.3
  progressive_projects_list      1.0.0
  project_overview               1.2.0
  recurring_tasks                1.3.0
  redmine_agile                  1.3.2
  redmine_code_review            0.6.3
  redmine_issue_checklist        2.0.5
  redmine_mentions               0.0.1
  redmine_revision_diff          0.1.1
  time_logger                    0.5.1
