### ISSUE TITLE
NoMethodError: undefined method `scoped'  - Redmine 3.03

### ISSUE THREAD

**Issue by ntonyl** [f0y/due_date_reminder#49]
When I try to send the notification i have this error : 

*\* Invoke redmine:reminder_plugin:send_notifications (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:reminder_plugin:send_notifications
rake aborted!
NoMethodError: undefined method `scoped' for #<Issue::ActiveRecord_Relation:0x00000004cf34e8>
/var/lib/gems/1.9.1/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:136:in`method_missing'
/var/lib/gems/1.9.1/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:99:in `method_missing'
/opt/redmine/redmine-3.0/plugins/due_date_reminder/app/models/reminder_mailer.rb:33:in`find_issues'
/opt/redmine/redmine-3.0/plugins/due_date_reminder/app/models/reminder_mailer.rb:15:in `due_date_notifications'
/opt/redmine/redmine-3.0/plugins/due_date_reminder/lib/tasks/reminder.rake:5:in`block (4 levels) in <top (required)>'
/opt/redmine/redmine-3.0/app/models/mailer.rb:383:in `with_synched_deliveries'
/opt/redmine/redmine-3.0/plugins/due_date_reminder/lib/tasks/reminder.rake:4:in`block (3 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in`block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in`execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in`invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in`block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in`top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in`standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in`<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in`<main>'
Tasks: TOP => redmine:reminder_plugin:send_notifications

**Comment by ardahaal** [comment]
Hi, I just had the same issue. Redmine 3.x uses Rails 4+ so method "scoped" is deprecated for models. Use "all" to match all objects or "where" to match some objects with conditions. You should be ok.

**Comment by ardahaal** [comment]
Hello again. Look here:
https://github.com/ardahaal/due_date_reminder/blob/redmine_3.1.x/app/models/reminder_mailer.rb
Line 32
